PATHS=""
if [ "$DO_CONSTRUCTIVE" = 'true' ]; then
  # generate:constructive also rewrites the meta-export manifest (it
  # enumerates the module config tables), so a new module leaves it
  # dirty; without it here the rebase below aborts on unstaged changes.
  # `application/constructive` covers both halves: deploy/ from the
  # generator, sql/ from the packaging step above.
  PATHS="$PATHS application/constructive sdk/constructive-schema/meta-export-tables.json"
fi
if [ "$DO_PLATFORM" = 'true' ]; then
  PATHS="$PATHS platform-schema"
fi

git add -A -- $PATHS

if git diff --cached --quiet; then
  echo "No changes — generated output already matches $BRANCH."
  echo 'changed=false' >> "$GITHUB_OUTPUT"
  exit 0
fi
echo 'changed=true' >> "$GITHUB_OUTPUT"

git diff --cached --stat

TARGETS=""
[ "$DO_CONSTRUCTIVE" = 'true' ] && TARGETS="constructive"
if [ "$DO_PLATFORM" = 'true' ]; then
  [ -n "$TARGETS" ] && TARGETS="$TARGETS + platform" || TARGETS="platform"
fi

git commit \
  -m "chore: regenerate $TARGETS" \
  -m "Generated by the Regenerate on a branch workflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
