BRANCH_NAME="schema-sdk-update/$(date -u +%Y%m%d-%H%M%S)"
git checkout -b "$BRANCH_NAME"
git add sdk/ application/ .agents/
git commit -m "chore: regenerate schemas, SDKs, and introspection output

Auto-generated by schema-sdk-update workflow.
Source: ${{ needs.generate.outputs.ref_sha }} (ref: ${{ inputs.ref || 'main' }})"

git push origin "$BRANCH_NAME"

PR_URL=$(gh pr create \
  --title "chore: regenerate schemas, SDKs, and introspection output" \
  --body "## Automated Schema Regeneration

This PR was created by the [schema-sdk-update workflow](${{ github.server_url }}/${{ github.repository }}/actions/workflows/schema-sdk-update.yml).

### What was regenerated
- \`application/constructive/\` — introspection output
- \`sdk/constructive-schema/schemas/\` — GraphQL schema files + introspection JSON
- \`sdk/sdk/\` — new SDK
- \`sdk/constructive-cli/\` — CLI
- \`sdk/constructive-sdk/\` — legacy SDK
- \`.agents/\` — skill reference docs

### Details
| Output | Changed |
|--------|---------|
| Introspection | ${{ needs.generate.outputs.has_introspection_changes }} |
| Schemas | ${{ needs.generate.outputs.has_schema_changes }} |
| SDKs + CLI | ${{ needs.generate.outputs.has_sdk_changes }} |
| Skills | ${{ needs.generate.outputs.has_agents_changes }} |

Source commit: \`${{ needs.generate.outputs.ref_sha }}\`

---
*Auto-generated by constructive-db schema-sdk-update workflow*" \
  --base "${{ inputs.ref || 'main' }}" \
  --head "$BRANCH_NAME")

echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
echo "Created PR: $PR_URL"
