import { Root, parse } from '@launchql/protobufjs';
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import * as t from '@babel/types';
import generate from '@babel/generator';

import {
  CelProtoParserOptions,
  ResolvedCelProtoParserOptions,
  getOptionsWithDefaults
} from './options';
import {
  convertTypeToTsInterface,
  generateNodeUnionType,
  generateAstHelperMethods,
  generateTypeImportSpecifiers,
  generateEnumImports
} from './ast';
import { convertEnumToTsUnionType, convertEnumToTsEnumDeclaration } from './ast/enums';
import { createDefaultImport, convertAstToCode } from './utils';
import { generateDeparserCode } from './deparser';

const GENERATED_HEADER = `/**
* This file was automatically generated by cel-proto-parser.
* DO NOT MODIFY IT BY HAND. Instead, modify the source proto file,
* and run the cel-proto-parser generate command to regenerate this file.
*/`;

interface ProtoField {
  name: string;
  type: string;
  rule?: string;
}

interface ProtoType {
  name: string;
  fields: Record<string, ProtoField>;
  nested?: Record<string, ProtoType | ProtoEnum>;
}

interface ProtoEnum {
  name: string;
  values: Record<string, number>;
}

function isProtoType(obj: ProtoType | ProtoEnum): obj is ProtoType {
  return 'fields' in obj;
}

function isProtoEnum(obj: ProtoType | ProtoEnum): obj is ProtoEnum {
  return 'values' in obj && !('fields' in obj);
}

export class CelProtoParser {
  private protoPath: string;
  private options: ResolvedCelProtoParserOptions;
  private root: Root | null = null;
  private types: ProtoType[] = [];
  private enums: ProtoEnum[] = [];

  constructor(protoPath: string, options?: CelProtoParserOptions) {
    this.protoPath = protoPath;
    this.options = getOptionsWithDefaults(options);
  }

  /**
   * Parse the proto file and extract types and enums
   */
  parse(): void {
    const protoContent = readFileSync(this.protoPath, 'utf-8');

    this.root = parse(protoContent, {
      keepCase: this.options.parser.keepCase
    }).root;

    this.extractTypesAndEnums(this.root);
  }

  /**
   * Extract types and enums from the parsed proto root
   */
  private extractTypesAndEnums(root: Root): void {
    const exclude = new Set(this.options.exclude);

    // Helper to recursively extract from nested structures
    const extract = (obj: Record<string, unknown>, prefix: string = '') => {
      for (const [key, value] of Object.entries(obj)) {
        if (!value || typeof value !== 'object') continue;

        const fullName = prefix ? `${prefix}.${key}` : key;

        // Skip excluded types
        if (exclude.has(key) || exclude.has(fullName)) continue;

        const item = value as ProtoType | ProtoEnum;

        if (isProtoType(item)) {
          // It's a message type
          this.types.push({
            name: key,
            fields: this.normalizeFields(item.fields),
            nested: item.nested
          });

          // Extract nested types
          if (item.nested) {
            extract(item.nested as Record<string, unknown>, fullName);
          }
        } else if (isProtoEnum(item)) {
          // It's an enum
          this.enums.push({
            name: key,
            values: item.values
          });
        }
      }
    };

    // Start extraction from root.nested
    if (root.nested) {
      extract(root.nested as Record<string, unknown>);
    }
  }

  /**
   * Normalize fields to ensure consistent structure
   */
  private normalizeFields(
    fields: Record<string, ProtoField> | undefined
  ): Record<string, ProtoField> {
    if (!fields) return {};

    const normalized: Record<string, ProtoField> = {};
    for (const [key, field] of Object.entries(fields)) {
      normalized[key] = {
        name: field.name || key,
        type: field.type,
        rule: field.rule
      };
    }
    return normalized;
  }

  /**
   * Generate all output files
   */
  write(): void {
    if (!this.root) {
      this.parse();
    }

    const { outDir } = this.options;
    mkdirSync(outDir, { recursive: true });

    if (this.options.enums.enabled) {
      this.writeEnums();
    }

    if (this.options.types.enabled) {
      this.writeTypes();
    }

    if (this.options.utils.astHelpers.enabled) {
      this.writeAstHelpers();
    }

    if (this.options.deparser.enabled) {
      this.writeDeparser();
    }
  }

  /**
   * Write enum definitions to file
   */
  private writeEnums(): void {
    const { outDir, enums: enumOptions } = this.options;
    const filePath = join(outDir, enumOptions.filename);

    const statements: t.Statement[] = [];

    for (const enumNode of this.enums) {
      if (enumOptions.enumsAsTypeUnion) {
        statements.push(convertEnumToTsUnionType(enumNode));
      } else {
        statements.push(convertEnumToTsEnumDeclaration(enumNode));
      }
    }

    const code = this.generateCode(statements);
    writeFileSync(filePath, code, 'utf-8');
  }

  /**
   * Write type definitions to file
   */
  private writeTypes(): void {
    const { outDir, types: typeOptions, enums: enumOptions } = this.options;
    const filePath = join(outDir, typeOptions.filename);

    const statements: t.Statement[] = [];

    // Add enum imports if there are enums
    if (this.enums.length > 0 && enumOptions.enabled) {
      const enumImport = generateEnumImports(
        this.enums,
        typeOptions.enumsSource
      );
      statements.push(enumImport);
    }

    // Generate Node union type
    if (this.types.length > 0) {
      statements.push(generateNodeUnionType(this.types));
    }

    // Generate interfaces for each type
    for (const type of this.types) {
      statements.push(convertTypeToTsInterface(type, this.options));
    }

    const code = this.generateCode(statements);
    writeFileSync(filePath, code, 'utf-8');
  }

  /**
   * Write AST helper functions to file
   */
  private writeAstHelpers(): void {
    const { outDir, utils } = this.options;
    const filePath = join(outDir, utils.astHelpers.filename);

    const statements: t.Statement[] = [];

    // Add nested-obj import
    statements.push(createDefaultImport('_o', 'nested-obj'));

    // Add type imports
    if (this.types.length > 0) {
      statements.push(generateTypeImportSpecifiers(this.types, this.options));
    }

    // Generate helper methods
    if (this.types.length > 0) {
      statements.push(generateAstHelperMethods(this.types));
    }

    const code = this.generateCode(statements);
    writeFileSync(filePath, code, 'utf-8');
  }

  /**
   * Write deparser module to file
   */
  private writeDeparser(): void {
    const { outDir, deparser: deparserOptions } = this.options;
    const filePath = join(outDir, deparserOptions.filename);

    const code = generateDeparserCode();
    writeFileSync(filePath, code, 'utf-8');
  }

  /**
   * Generate TypeScript code from AST statements
   */
  private generateCode(statements: t.Statement[]): string {
    const program = t.program(statements);
    const { code } = generate(program, { comments: true });
    return `${GENERATED_HEADER}\n${code}\n`;
  }

  /**
   * Get the parsed types
   */
  getTypes(): ProtoType[] {
    return this.types;
  }

  /**
   * Get the parsed enums
   */
  getEnums(): ProtoEnum[] {
    return this.enums;
  }
}
