import { Document, parseDocument } from 'yaml';

import { applyComments, fromYaml, toYaml } from '../src';

describe('toYaml comments', () => {
  it('serializes without comments by default', () => {
    expect(toYaml({ name: 'app', replicas: 3 })).toBe('name: app\nreplicas: 3\n');
  });

  it('writes a header block above the document', () => {
    const out = toYaml(
      { minimumReleaseAge: 20160 },
      { comments: { header: 'Generated by pnpm-policy.\nDo not edit by hand.' } }
    );
    expect(out).toBe(
      '# Generated by pnpm-policy.\n# Do not edit by hand.\n\nminimumReleaseAge: 20160\n'
    );
  });

  it('writes a footer block below the document', () => {
    const out = toYaml({ a: 1 }, { comments: { footer: 'end' } });
    expect(out).toBe('a: 1\n\n# end\n');
  });

  it('writes a comment above a top-level key', () => {
    const out = toYaml(
      { packages: ['packages/*'], minimumReleaseAge: 20160 },
      { comments: { before: { minimumReleaseAge: '14 days, in minutes.' } } }
    );
    expect(out).toContain('# 14 days, in minutes.\nminimumReleaseAge: 20160');
  });

  it('writes a comment above a nested key', () => {
    const out = toYaml(
      { security: { minimumReleaseAge: 20160 } },
      { comments: { before: { 'security.minimumReleaseAge': 'third-party only' } } }
    );
    expect(out).toContain('  # third-party only\n  minimumReleaseAge: 20160');
  });

  it('writes a comment above a sequence item addressed by index', () => {
    const out = toYaml(
      { allowBuilds: ['esbuild', 'core-js'] },
      { comments: { before: { 'allowBuilds.1': 'polyfills, needs its postinstall' } } }
    );
    expect(out).toContain('# polyfills, needs its postinstall\n  - core-js');
  });

  it('writes an inline comment on a key line', () => {
    const out = toYaml(
      { blockExoticSubdeps: true },
      { comments: { inline: { blockExoticSubdeps: 'no git/tarball subdeps' } } }
    );
    expect(out).toBe('blockExoticSubdeps: true # no git/tarball subdeps\n');
  });

  it('ignores paths that do not resolve', () => {
    const out = toYaml({ a: 1 }, { comments: { before: { 'b.c': 'nope' } } });
    expect(out).toBe('a: 1\n');
  });

  it('round-trips: comments do not change the parsed value', () => {
    const value = { security: { minimumReleaseAge: 20160 }, allowBuilds: ['esbuild'] };
    const out = toYaml(value, {
      comments: {
        header: 'generated',
        before: { 'security.minimumReleaseAge': 'why' },
        inline: { allowBuilds: 'trusted' }
      }
    });
    expect(fromYaml(out)).toEqual(value);
  });

  it('does not wrap long values by default', () => {
    const long = 'x'.repeat(200);
    expect(toYaml({ long })).toBe(`long: ${long}\n`);
  });
});

describe('applyComments', () => {
  it('annotates entries added with Document.set, which stores plain values', () => {
    const doc = new Document({});
    doc.set('minimumReleaseAge', 20160);
    doc.set('allowBuilds', { esbuild: true });
    applyComments(doc, {
      before: { minimumReleaseAge: 'the wait' },
      inline: [[['allowBuilds', 'esbuild'], 'native binary']]
    });
    expect(doc.toString()).toBe(
      '# the wait\nminimumReleaseAge: 20160\nallowBuilds:\n  esbuild: true # native binary\n'
    );
  });

  it('addresses a key containing a dot through an explicit path', () => {
    const doc = parseDocument('deps:\n  lodash.merge: true\n');
    applyComments(doc, { inline: [[['deps', 'lodash.merge'], 'why not']] });
    expect(doc.toString()).toContain('lodash.merge: true # why not');
  });

  it('leaves comments on keys it was not asked about', () => {
    const doc = parseDocument('# hand-written\npackages:\n  - packages/*\nage: 1\n');
    applyComments(doc, { before: { age: 'the wait' } });
    const out = doc.toString();
    expect(out).toContain('# hand-written');
    expect(out).toContain('# the wait\nage: 1');
  });

  it('replaces the comment on a key it is asked about', () => {
    const doc = parseDocument('# stale\nage: 1\n');
    applyComments(doc, { before: { age: 'current' } });
    expect(doc.toString()).toBe('# current\nage: 1\n');
  });

  it('opens a blank line when the comment starts with one', () => {
    const doc = parseDocument('packages:\n  - packages/*\n');
    doc.set('age', 1);
    applyComments(doc, { before: { age: '\nthe wait' } });
    expect(doc.toString()).toBe('packages:\n  - packages/*\n\n# the wait\nage: 1\n');
  });

  it('does not open one otherwise', () => {
    const doc = parseDocument('packages:\n  - packages/*\n');
    doc.set('age', 1);
    applyComments(doc, { before: { age: 'the wait' } });
    expect(doc.toString()).toBe('packages:\n  - packages/*\n# the wait\nage: 1\n');
  });
});
